apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::264353213671:role/UdacityOPBcoFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::264353213671:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-838N3JTYYRI9
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T09:50:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1705"
  uid: 1b9d9d80-b9a1-4f08-9d96-e38425c70533
